// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/models/city_model.dart' as _i2;
import 'package:weather_app/models/city_weather_model.dart' as _i3;
import 'package:weather_app/repository/weather_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCity_0 extends _i1.SmartFake implements _i2.City {
  _FakeCity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCityWeather_1 extends _i1.SmartFake implements _i3.CityWeather {
  _FakeCityWeather_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i4.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.City>> getCityList() =>
      (super.noSuchMethod(
            Invocation.method(#getCityList, []),
            returnValue: _i5.Future<List<_i2.City>>.value(<_i2.City>[]),
          )
          as _i5.Future<List<_i2.City>>);

  @override
  _i5.Future<_i2.City> saveCity(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#saveCity, [cityName]),
            returnValue: _i5.Future<_i2.City>.value(
              _FakeCity_0(this, Invocation.method(#saveCity, [cityName])),
            ),
          )
          as _i5.Future<_i2.City>);

  @override
  _i5.Future<_i2.City> deleteCity(int? cityID) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCity, [cityID]),
            returnValue: _i5.Future<_i2.City>.value(
              _FakeCity_0(this, Invocation.method(#deleteCity, [cityID])),
            ),
          )
          as _i5.Future<_i2.City>);

  @override
  _i5.Future<_i3.CityWeather> fetchCityWeatherDetails(_i2.City? city) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCityWeatherDetails, [city]),
            returnValue: _i5.Future<_i3.CityWeather>.value(
              _FakeCityWeather_1(
                this,
                Invocation.method(#fetchCityWeatherDetails, [city]),
              ),
            ),
          )
          as _i5.Future<_i3.CityWeather>);
}
